In [91]:
import pandas as pd

In [4]:
data = pd.read_csv('../raw_data/dataset.csv',sep=';')
data.head()

,uuid,default,account_amount_added_12_24m,account_days_in_dc_12_24m,account_days_in_rem_12_24m,account_days_in_term_12_24m,account_incoming_debt_vs_paid_0_24m,account_status,account_worst_status_0_3m,account_worst_status_12_24m,...,status_3rd_last_archived_0_24m,status_max_archived_0_6_months,status_max_archived_0_12_months,status_max_archived_0_24_months,recovery_debt,sum_capital_paid_account_0_12m,sum_capital_paid_account_12_24m,sum_paid_inv_0_12m,time_hours,worst_status_active_inv
0,63f69b2c-8b1c-4740-b78d-52ed9a4515ac,0.0,0,0.0,0.0,0.0,0.0,1.0,1.0,NaN,...,1,1,1,1,0,0,0,178839,9.653333,1.0
1,0e961183-8c15-4470-9a5e-07a1bd207661,0.0,0,0.0,0.0,0.0,NaN,1.0,1.0,1.0,...,1,1,2,2,0,0,0,49014,13.181389,NaN
2,d8edaae6-4368-44e0-941e-8328f203e64e,0.0,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,...,1,1,2,2,0,0,0,124839,11.561944,1.0
3,0095dfb6-a886-4e2a-b056-15ef45fdb0ef,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,1,1,0,0,0,324676,15.751111,1.0
4,c8f8b835-5647-4506-bf15-49105d8af30b,0.0,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,...,0,1,1,1,0,0,0,7100,12.698611,NaN

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99976 entries, 0 to 99975
Data columns (total 43 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   uuid                                 99976 non-null  object
 1   default                              89976 non-null  float64
 2   account_amount_added_12_24m          99976 non-null  int64
 3   account_days_in_dc_12_24m            88140 non-null  float64
 4   account_days_in_rem_12_24m           88140 non-null  float64
 5   account_days_in_term_12_24m          88140 non-null  float64
 6   account_incoming_debt_vs_paid_0_24m  40661 non-null  float64
 7   account_status                       45603 non-null  float64
 8   account_worst_status_0_3m            45603 non-null  float64
 9   account_worst_status_12_24m          33215 non-null  float64
 10  account_worst_status_3_6m            42274 non-null  float64
 11  account_worst_status_6_12m           39626 non-null  float64
 12  age                                  99976 non-null  int64
 13  avg_payment_span_0_12m               76140 non-null  float64
 14  avg_payment_span_0_3m                50671 non-null  float64
 15  merchant_category                    99976 non-null  object
 16  merchant_group                       99976 non-null  object
 17  has_paid                             99976 non-null  bool
 18  max_paid_inv_0_12m                   99976 non-null  float64
 19  max_paid_inv_0_24m                   99976 non-null  float64
 20  name_in_email                        99976 non-null  object
 21  num_active_div_by_paid_inv_0_12m     77037 non-null  float64
 22  num_active_inv                       99976 non-null  int64
 23  num_arch_dc_0_12m                    99976 non-null  int64
 24  num_arch_dc_12_24m                   99976 non-null  int64
 25  num_arch_ok_0_12m                    99976 non-null  int64
 26  num_arch_ok_12_24m                   99976 non-null  int64
 27  num_arch_rem_0_12m                   99976 non-null  int64
 28  num_arch_written_off_0_12m           81898 non-null  float64
 29  num_arch_written_off_12_24m          81898 non-null  float64
 30  num_unpaid_bills                     99976 non-null  int64
 31  status_last_archived_0_24m           99976 non-null  int64
 32  status_2nd_last_archived_0_24m       99976 non-null  int64
 33  status_3rd_last_archived_0_24m       99976 non-null  int64
 34  status_max_archived_0_6_months       99976 non-null  int64
 35  status_max_archived_0_12_months      99976 non-null  int64
 36  status_max_archived_0_24_months      99976 non-null  int64
 37  recovery_debt                        99976 non-null  int64
 38  sum_capital_paid_account_0_12m       99976 non-null  int64
 39  sum_capital_paid_account_12_24m      99976 non-null  int64
 40  sum_paid_inv_0_12m                   99976 non-null  int64
 41  time_hours                           99976 non-null  float64
 42  worst_status_active_inv              30461 non-null  float64
dtypes: bool(1), float64(19), int64(19), object(4)
memory usage: 32.1+ MB

### Data set

In [14]:
f'we have info of {len(data)} clients'

'we have info of 99976 clients'

### Features
This explantion comes from this [GitHub repo (ottk92)](https://github.com/ottok92/default_prediction_case_study/blob/master/src/1_sanity/basic_profile.ipynb)

Please, also take a look at his analysis

  **Personal variables**
  1. age
  2. name_in_email

  **Status variables**
  
  They seem to be ordinal (hence the max in some of them), with 1.0 being the normal status and 4.0 being the worst. From the principle "customer obssession", it seems reasonable to assume missing values should default to 1.0. In other words, the account is considered normal until proven otherwise.

  3. account_status: `the current status of the account`
  4. account_worst_status_M_Nm: `the worst status (max) in the M to N period in months`
  5. account_days_in_dc_M_Nm: `number of days an account was put into status "dc" between M and N months ago (?)`
  6. account_days_in_rem_M_Nm: `number of days an account was put into status "rem" between M and N months ago (?)`
  7. account_days_in_term_M_Nm: `number of days an account was put into status "term" between M and N months ago (terminated ?)`
  8. status_max_archived_M_N_months: `the max (worst) status for archieved invoices`
  9. status_Nth_archived_M_Nm: `status of the last Nth archived invoice between M and N months ago`
    `0 through 5, with 1 being the most commom status... perhaps:`

      -  `0 means paid on the spot`  

      -  `1 means paid fully in short term installments`

      -  `2 means paid fully in longer term installments`

      -  `3 means paid fully in installments with fee due to 
        delays in payment`

      -  `4 means not paid in full (is not present in the train dataset)`
        
      -  `5 means not paid at all`
        
  **Account variables**
  
  11. account_amount_added_12_24m: `money deposited into the app for cardless purchases`
  
  12. sum_capital_paid_account_M_Nm: `the total amount of money paid with account funds between M and N months ago`
  13. account_incoming_debt_vs_paid_0_24m: `ratio "new_debt / old_paid_debt"`
  14. num_unpaid_bills: `number of installments still unpaid`
  15. sum_paid_inv_0_12m: `the total amount of money paid with installments (card) between M and N  months ago`
  16. max_paid_inv_M_Nm: `the amount of the largest purchase the account has made between M and N months ago`
  17. num_active_inv: `number of active invoices`
  18. num_active_div_by_paid_inv_M_Nm: `ratio "number_active_invoices / number_paid_invoices" between M and N months ago`
    `null when number_paid_invoices is zero`
    `can be imputed, what's the best way?`
  19. avg_payment_span_M_Nm: `the average number of days to liquidate debt looking back between M and  N months ago`
  20. has_paid: `whether the account has paid the latest installment`

  **Archived variables**

  21. num_arch_dc_M_Nm: `number of archieved invoices with status "dc" between M and N months ago (?)`
  
  22. num_arch_ok_M_Nm: `number of archieved invoices with status "ok" between M and N months ago`
  23. num_arch_rem_M_Nm: `number of archieved invoices with status "rem" between M and N months ago (?)`
  24. num_arch_written_off_M_Nm: `number of archieved invoices that were unpaid between M and N months ago`
  
**Order variables**

  25. merchant_category: `category of the merchant receiving the order`

  26. merchant_group: `group of the merchant receiving the order`

**Not inclueded** 

At this point not going to remove any feature

  27. has_paid: `we've either True or False values and most of are True`

  28. recovery_debt:`it's numeric and we have diferent amount. Probably, these clients have default at a certain moment`
  29. time_hours: `it may mean the hours spent in the app`
  30. worst_status_active_inv: `in the next steps we can remove this feature once all values are missing`

In [66]:
# has_paid feature
has_paid_true = len(data['has_paid'][data['has_paid'] == True]) / len(data)
has_paid_missing = data['has_paid'].isna().sum()
unique_values = data['has_paid'].unique()

print(f'we have either True or False {unique_values }')
print(f'{round(has_paid_true*100, 2)}% are True values and we have {has_paid_missing} missing values')

we have either True or False [ True False]
85.12% are True values and we have 0 missing values

In [62]:
# recovery_debt
rec_debt = data['recovery_debt'].isna().sum()
client_defaults_amounts = len(data['recovery_debt'][data['recovery_debt'] > 0])
print(f'we have {rec_debt} missing values')
print(f'we have {client_defaults_amounts} with default amounts')

we have 0 missing values
we have 222 with default amounts

In [81]:
# time_hours
print(data['time_hours'].describe())
time_hours_missing = data['time_hours'].isna().sum()
print(f'we have {time_hours_missing} missing values')

count    99976.000000
mean        15.329780
std          5.031360
min          0.000278
25%         11.622708
50%         15.792778
75%         19.542014
max         23.999722
Name: time_hours, dtype: float64
we have 0 missing values

In [90]:
# worst_status_active_inv'
worst_status_active_inv_missing = len(data['worst_status_active_inv'].isna()) / len(data)
print(f'{worst_status_active_inv_missing*100}% of the values are missing')

100.0% of the values are missing